[package]
name = "sqf"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.6"
pest_derive = "2.6"
lazy_static = "*"

[dev-dependencies]
clap = {version = "*", features = ["cargo"]}
source-span = "*"

[[example]]
name = "sqf-analyzer"
